name: slide_to_confirm
description: A slider that will activate a callback when the user slides it to 100%.
version: 1.1.0
author: Gustav Friis-Hansen <friisdeveloper@gmail.com>
homepage: https://github.com/Friiiis/slide_to_confirm

environment:
  sdk: ">3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
